### ISSUE TITLE
Problem when robots.txt lines starts with some spaces

### ISSUE THREAD

**Issue by shulard** [bee4/robots.txt#6]
If the `robots.txt` file is not well formed and lines starts with spaces, the parser match nothing.

```
    # Google Image Crawler Setup
    User-agent: Googlebot-Image
    Disallow:

    # Crawlers Setup
    User-agent: *

    # Site Map
    Sitemap: http://www.tradediscount.com/sitemap.xml

    # Directories
    Disallow: /404/
    Disallow: /app/
    Disallow: /cgi-bin/
    Disallow: /downloader/
    Disallow: /errors/
    Disallow: /includes/
    #Disallow: /js/
    #Disallow: /lib/
    Disallow: /magento/
    #Disallow: /media/
    Disallow: /pkginfo/
    Disallow: /report/
    Disallow: /scripts/
    Disallow: /shell/
    Disallow: /skin/
    Disallow: /stats/
    Disallow: /var/
```

When parsing there is just no rules in the result...
